### ISSUE TITLE
Use WSGI server for API

### ISSUE THREAD

**Issue by ctgraham** [ulsdevteam/ccvgd-integral#8]
The default Dockerfile for ccvgd-backend uses the built-in Python development server and is unsuitable for production use:
https://github.com/ulsdevteam/ccvgd-backend/blob/a229232a4dbb6d178ac76144a134a423cb5e28a5/Dockerfile#L13

Logs:
```
 * Serving Flask app "manager" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
```

We should instead use a WSGI build of Apache (or similar) in a production Dockerfile.  That Dockerfile should be referenced in this docker compose when the PRODUCTION environment variable is set.

It is more complicated than we need here, but see an example of such here:
https://github.com/RockefellerArchiveCenter/request_broker/pull/245

**Comment by Caligula1022** [comment]
Got it. Another step closer to success.

**Comment by Caligula1022** [comment]
I'm having trouble with a PermissionError here.

### Here's the error log:

ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140663 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140664 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     reraise(exc_type, exc_value, tb)
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140666 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140668 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     raise value
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140670 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140671 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     response = self.full_dispatch_request()
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140673 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140675 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     rv = self.handle_user_exception(e)
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140676 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140678 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     reraise(exc_type, exc_value, tb)
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140680 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140681 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     raise value
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140780 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140798 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     rv = self.dispatch_request()
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140806 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140808 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     return self.view_functions[rule.endpoint](**req.view_args)
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140810 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]   File "/var/www/apache-flask/app_func/advance_search.py", line 172, in advanceSearch
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140811 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680]     f = open(os.path.join(path, "app_func", "multiple_csv",
ccvgd-integral-ccvg-1     | [Tue Oct 11 05:02:12.140819 2022] [wsgi:error] [pid 10:tid 281473568186752] [remote 172.28.0.5:55680] PermissionError: [Errno 13] Permission denied: '/var/www/apache-flask/app_func/multiple_csv/19_32_village.csv'
ccvgd-integral-ccvg-1     | 172.28.0.5 - - [11/Oct/2022:05:02:11 +0000] "POST /advancesearch HTTP/1.1" 500 810 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0"


### Here's the dockerfile:

`
FROM python:3.9

RUN apt-get update
RUN apt-get install --yes apache2 apache2-dev
RUN apt-get -y install python3-pip
RUN apt-get install libapache2-mod-wsgi-py3
RUN pip install --upgrade pip

RUN wget https://github.com/GrahamDumpleton/mod_wsgi/archive/refs/tags/4.9.0.tar.gz \
    && tar xvfz 4.9.0.tar.gz \
    && cd mod_wsgi-4.9.0 \
    && ./configure --with-apxs=/usr/bin/apxs --with-python=/usr/local/bin/python3.9 \
    && make \
    && make install \
    && make clean


ADD wsgi.load /etc/apache2/mods-available/wsgi.load

COPY ./apache-flask.conf /etc/apache2/sites-available/apache-flask.conf

RUN a2dissite 000-default.conf
RUN a2ensite apache-flask.conf
RUN a2enmod headers
RUN a2enmod rewrite
RUN a2enmod wsgi

RUN adduser --system --group --disabled-login ccvguser; cd /home/ccvguser/


COPY . /var/www/apache-flask/
RUN chown ccvguser:www-data -R /var/www/apache-flask/
WORKDIR /var/www/apache-flask/
RUN pip install --no-cache-dir -r requirements_dev.txt


RUN ln -sf /proc/self/fd/1 /var/log/apache2/access.log && \
    ln -sf /proc/self/fd/1 /var/log/apache2/error.log


EXPOSE 80


CMD  /usr/sbin/apache2ctl -D FOREGROUND
`

### This is my conf file:

`
<VirtualHost *:80>

    # Python application integration
    WSGIDaemonProcess /apache-flask python-path=/var/www/apache-flask/:/usr/local/bin/python3.9
    WSGIProcessGroup /apache-flask
    WSGIScriptAlias / /var/www/apache-flask/apache-flask.wsgi

    <Directory "/var/www/apache-flask/">
        Header set Access-Control-Allow-Origin "*"
        WSGIProcessGroup /apache-flask
        WSGIApplicationGroup %{GLOBAL}
        Options +ExecCGI
        Order deny,allow
        Allow from all
    </Directory>
    Alias /static /var/www/apache-flask/static
    <Directory /var/www/apache-flask/static>
        Order allow,deny
        Allow from all
    </Directory>
    ErrorLog ${APACHE_LOG_DIR}/error.log
    LogLevel warn
    CustomLog ${APACHE_LOG_DIR}/access.log combined

</VirtualHost>
`

### Here is my wsgi file:

`#! /usr/local/bin/python3.9

from app import app as application

import sys

sys.path.append("/var/www/apache-flask")`

**Comment by ctgraham** [comment]
Can you publish this to a feature branch so that I can reproduce it?

**Comment by Caligula1022** [comment]
Sure

From: Clinton Graham ***@***.***>
Date: Tuesday, October 11, 2022 at 12:43 PM
To: ulsdevteam/ccvgd-integral ***@***.***>
Cc: Yifei Tai ***@***.***>, Assign ***@***.***>
Subject: Re: [ulsdevteam/ccvgd-integral] Use WSGI server for API (Issue #8)

Can you publish this to a feature branch so that I can reproduce it?

**Comment by Caligula1022** [comment]
Uploaded to the new branch.

**Comment by ctgraham** [comment]
Found as https://github.com/ulsdevteam/ccvgd-backend/tree/wsgi_test_backend .

For future reference, note that if you make a commit message which references this issue number (e.g. `ccvgd-integral#8: add wsgi file to new branch`), Github will automatically do convenience linking for you.

**Comment by Caligula1022** [comment]
Got you.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ctgraham** [comment]
I performed a build of the application with the `wsgi_test_backend` branch, but I didn't see the permissions error in the build, or in the logs from `sudo docker logs ccvgd-ccvg-1`.  Is there anything specific I need to do to generate this error message?

**Comment by Caligula1022** [comment]
You need to access the website and do a random search. This error then appears.

**Comment by ctgraham** [comment]
Aside: Note that the apt-get install of `libapache2-mod-wsgi-py3` here:
https://github.com/ulsdevteam/ccvgd-backend/blob/75d1c7c8d2412e12d9c83b29736de420344b6fd1/Dockerfile#L6
is the equivalent of the manual build and install here:
https://github.com/ulsdevteam/ccvgd-backend/blob/75d1c7c8d2412e12d9c83b29736de420344b6fd1/Dockerfile#L9-L15
You shouldn't need the manual `wget` and `make`.  Not needing to build wsgi from source also should eliminate the need for the `apache2-dev` package here:
https://github.com/ulsdevteam/ccvgd-backend/blob/75d1c7c8d2412e12d9c83b29736de420344b6fd1/Dockerfile#L4

**Comment by Caligula1022** [comment]
Got it. 👌

**Comment by ctgraham** [comment]
I tried selecting some random criteria and clicking the search button in the lower right.  I did receive some errors in the logs for the backend container, but not matching your message.  Selected examples:
```
[Tue Oct 11 20:48:57.469180 2022] [wsgi:error] [pid 10:tid 140209219831552] [remote 192.168.160.5:43028] This village id is not have fourth last name
[Tue Oct 11 20:48:57.489111 2022] [wsgi:error] [pid 10:tid 140209286973184] [remote 192.168.160.5:43024] [Errno 36] File name too long: '/var/www/apache-flask/app_func/multiple_csv/1_3_4_5_6_7_8_9_10_11_12_13_14_15_16_17_18_19_20_21_22_23_24_25_26_27_28_29_30_31_32_33_34_35_36_37_38_39_40_41_42_43_44_45_47_48_49_50_51_53_54_55_56_57_59_60_61_62_63_64_65_66_67_68_69_70_72_73_74_75_76_79_80_81_82_83_84_85_86_87_88_89_90_91_92_93_94_95_96_97_98_99_100_101_102_103_104_105_106_107_108_109_110_111_112_113_114_115_116_117_118_119_120_121_123_124_125_126_127_128_129_130_131_132_133_134_135_136_137_138_139_140_141_142_143_144_145_146_147_148_149_150_151_152_153_154_156_157_158_159_160_161_162_163_164_165_166_167_168_169_170_171_172_173_174_176_177_178_179_180_181_183_184_185_186_187_188_189_190_191_192_193_194_195_196_197_198_199_200_201_203_204_205_206_207_208_209_210_211_212_213_214_215_216_217_218_219_220_221_222_223_224_225_226_227_228_229_230_231_232_233_234_235_236_238_239_241_242_243_244_245_246_247_248_249_250_251_252_253_254_255_256_257_258_259_260_261_262_263_264_265_266_267_268_269_270_271_272_273_274_277_278_279_280_281_282_283_285_286_287_288_289_290_291_292_293_294_295_296_297_298_299_300_301_302_303_304_305_306_307_309_310_312_313_314_315_316_317_318_319_320_321_322_323_324_325_326_327_330_331_332_333_334_335_336_337_338_339_340_341_343_344_345_346_347_348_349_350_351_352_353_354_355_356_357_358_359_360_361_362_363_364_365_366_367_368_369_370_371_372_373_374_375_376_377_378_379_380_381_382_383_384_385_386_387_389_390_391_392_393_394_395_396_397_398_399_400_401_402_404_405_406_407_408_409_411_412_413_414_415_416_417_418_419_420_421_422_423_424_425_427_428_429_430_432_433_434_436_437_438_439_440_441_443_444_445_446_447_448_449_450_451_452_453_454_455_456_457_458_459_460_461_462_463_464_465_466_467_468_470_471_472_473_474_475_476_477_478_479_480_481_482_483_484_485_486_487_488_489_490_491_492_493_494_495_496_497_498_499_500_501_502_503_504_505_506_507_508_509_510_511_512_513_514_515_516_517_518_519_521_522_523_524_525_526_527_528_529_530_531_532_533_534_535_536_537_538_539_540_541_542_543_544_545_546_547_548_549_550_551_552_553_554_555_556_557_558_559_560_561_562_563_564_565_566_567_568_569_570_571_572_573_574_575_576_577_578_579_580_581_582_583_584_585_586_587_588_589_590_591_592_593_594_595_596_597_598_599_600_601_602_603_604_605_606_607_609_610_611_612_613_614_615_616_617_618_619_620_621_622_623_624_625_626_627_628_629_630_631_632_633_634_635_636_637_638_639_640_641_642_643_644_645_646_647_648_650_651_652_653_654_655_656_658_659_660_662_663_664_665_666_667_668_669_670_671_673_674_675_676_677_678_679_680_681_682_683_684_685_686_687_688_689_690_691_692_693_694_695_696_697_698_699_700_701_702_703_704_705_706_707_708_709_710_711_712_713_714_715_716_718_719_720_721_722_723_724_725_726_727_728_729_730_731_732_733_734_735_736_737_738_739_740_741_742_743_744_745_746_747_748_749_750_751_752_753_754_755_756_757_758_759_760_761_762_763_764_765_766_767_768_769_770_771_772_773_774_775_776_777_778_779_780_781_782_783_784_785_786_787_788_789_790_791_792_793_794_795_796_797_798_799_800_801_802_803_804_805_806_807_808_809_810_811_812_813_814_815_816_818_819_820_821_822_823_824_825_826_827_828_829_830_831_832_833_834_835_836_839_840_841_842_843_844_845_846_847_848_849_850_851_852_853_854_855_856_857_858_859_860_861_862_863_864_865_866_867_868_869_870_871_872_873_874_875_876_877_878_879_880_881_882_883_884_885_886_887_888_889_890_891_892_893_894_895_896_897_898_899_900_901_902_903_904_905_906_907_908_909_910_911_912_913_914_915_916_917_918_919_920_921_922_923_924_925_926_927_928_929_930_931_932_933_934_935_936_937_938_939_940_941_942_943_944_945_946_947_949_950_951_952_953_954_955_956_957_958_959_960_961_962_963_964_965_966_967_968_969_970_971_972_974_975_976_977_978_979_980_981_982_983_984_986_987_988_989_990_991_992_993_994_995_996_997_998_999_1000_1002_1003_1004_1005_1006_1007_1008_1009_1010_1011_1012_1013_1014_1015_1016_1017_1018_1019_1020_1021_1022_1023_1024_1025_1026_1027_1028_1030_1031_1032_1033_1034_1035_1036_1037_1038_1039_1040_1041_1042_1043_1044_1045_1046_1047_1048_1049_1050_1051_1052_1053_1054_1055_1056_1057_1058_1059_1060_1061_1062_1063_1064_1065_1066_1067_1068_1069_1070_1071_1073_1074_1075_1076_1077_1078_1079_1080_1081_1082_1083_1084_1085_1086_1087_1088_1089_1090_1091_1093_1094_1095_1096_1097_1098_1099_1100_1101_1102_1103_1104_1105_1106_1107_1108_1109_1110_1111_1112_1113_1114_1115_1116_1117_1118_1119_1120_1124_1125_1126_1127_1128_1129_1130_1131_1132_1133_1134_1135_1136_1137_1138_1139_1140_1141_1142_1143_1144_1145_1146_1147_1148_1149_1150_1151_1152_1153_1154_1155_1156_1157_1158_1159_1160_1161_1162_1163_1164_1165_1166_1167_1168_1169_1170_1171_1172_1173_1174_1175_1176_1177_1178_1179_1180_1181_1182_1183_1184_1185_1186_1187_1188_1190_1191_1192_1193_1195_1196_1197_1198_1199_1200_1201_1203_1204_1205_1206_1208_1209_1210_1211_1212_1213_1214_1215_1216_1218_1219_1220_1221_1222_1223_1224_1225_1226_1227_1228_1229_1230_1231_1233_1234_1235_1236_1237_1238_1239_1240_1241_1243_1245_1246_1247_1248_1249_1251_1252_1253_1254_1255_1256_1257_1258_1259_1260_1261_1262_1263_1264_1265_1266_1267_1268_1269_1270_1271_1272_1273_1275_1277_1278_1279_1280_1281_1282_1283_1284_1285_1286_1287_1288_1289_1290_1291_1292_1293_1294_1295_1296_1298_1299_1300_1301_1302_1303_1304_1305_1307_1308_1309_1310_1311_1312_1313_1314_1315_1316_1317_1318_1319_1320_1321_1322_1323_1324_1325_1326_1327_1329_1330_1331_1332_1333_1334_1335_1336_1337_1338_1339_1340_1341_1342_1343_1344_1345_1346_1349_1350_1351_1352_1353_1354_1355_1356_1357_1358_1359_1360_1361_1362_1363_1364_1365_1366_1367_1368_1370_1371_1372_1373_1374_1375_1376_1377_1378_1379_1380_1381_1382_1383_1384_1385_1386_1387_1388_1389_1390_1391_1392_1393_1394_1395_1396_1397_1398_1399_1400_1402_1403_1404_1405_1406_1407_1408_1409_1410_1411_1412_1413_1414_1415_1416_1417_1418_1419_1420_1421_1422_1423_1424_1425_1426_1427_1428_1429_1430_1431_1432_1433_1434_1435_1436_1437_1438_1439_1440_1441_1442_1443_1444_1445_1446_1447_1448_1449_1450_1451_1452_1453_1454_1455_1456_1457_1458_1459_1460_1463_1464_1466_1467_1468_1469_1470_1472_1473_1474_1475_1476_1477_1478_1479_1480_1481_1482_1483_1484_1485_1486_1487_1488_1489_1490_1491_1492_1493_1494_1495_1497_1498_1499_1500_1501_1503_1504_1505_1506_1507_1508_1509_1510_1511_1512_1513_1514_1515_1516_1517_1518_1519_1520_1521_1522_1523_1524_1525_1526_1527_1528_1530_1531_1532_1533_1534_1535_1536_1537_1538_1539_1540_1541_1542_1543_1544_1545_1546_1547_1548_1549_1550_1551_1552_1553_1554_1555_1556_1557_1558_1559_1560_1561_1562_1563_1564_1565_1566_1567_1568_1569_1570_1571_1572_1573_1574_1575_1576_1577_1578_1579_1580_1581_1582_1583_1584_1585_1586_1587_1588_1589_1590_1591_1592_1593_1594_1595_1596_1597_1598_1599_1600_1601_1602_1603_1604_1605_1606_1607_1608_1609_1610_1611_1612_1613_1614_1615_1616_1617_1618_1619_1620_1621_1622_1623_1624_1625_1626_1627_1628_1629_1630_1631_1632_1633_1634_1635_1636_1637_1638_1639_1640_1641_1642_1643_1644_1645_1646_1647_1648_1649_1650_1651_1652_1653_1654_1655_1656_1657_1658_1659_1660_1661_1662_1663_1664_1665_1666_1667_1668_1669_1670_1671_1672_1673_1674_1675_1676_1677_1678_1679_1680_1681_1682_1683_1685_1686_1687_1688_1689_1690_1691_1692_1693_1694_1695_1696_1697_1698_1699_1700_1701_1702_1703_1704_1706_1707_1708_1709_1710_1711_1712_1713_1714_1715_1716_1717_1718_1719_1720_1721_1722_1724_1725_1726_1727_1728_1729_1730_1731_1732_1733_1734_1735_1736_1737_1738_1739_1740_1741_1742_1743_1744_1745_1746_1747_1748_1749_1750_1751_1752_1753_1754_1755_1756_1757_1758_1759_1760_1761_1762_1763_1764_1765_1766_1767_1768_1770_1771_1772_1773_1774_1775_1776_1777_1778_1779_1780_1781_1782_1783_1784_1785_1786_1790_1791_1792_1794_1795_1796_1797_1798_1800_1801_1803_1804_1805_1806_1807_1808_1809_1810_1811_1812_1813_1814_1815_1816_1817_1818_1820_1821_1822_1824_1825_1826_1827_1828_1829_1830_1831_1832_1833_1834_1835_1836_1837_1838_1839_1840_1841_1842_1843_1844_1845_1847_1848_1849_1850_1851_1852_1853_1854_1855_1856_1857_1858_1859_1861_1862_1863_1864_1865_1866_1867_1868_1869_1870_1871_1872_1873_1874_1875_1876_1878_1879_1880_1881_1882_1883_1884_1885_1886_1887_1888_1889_1890_1891_1892_1893_1894_1895_1896_1897_1899_1900_1901_1902_1903_1904_
[Tue Oct 11 20:49:14.226189 2022] [wsgi:error] [pid 10:tid 140209286973184] [remote 192.168.160.5:43238] No columns to parse from file
```

There does appear to be a lot of debugging output in the log.

Can you describe what specific values you selected?

**Comment by Caligula1022** [comment]
What I tried was like this:

<img width="1429" alt="image" src="https://user-images.githubusercontent.com/89871210/195198561-f05efbfc-3b1b-4bc3-bfc3-0c3ed5d1ca61.png">

**Comment by Caligula1022** [comment]
I encountered the same error as you when I select all villages. Seems like another issue.

**Comment by Caligula1022** [comment]
Hello Clinton,
It's been a long time. How's it going?
I specified the apache-flask file permissions in the dockerfile, so the “permission denied” problem was solved. Do you think this is okay?
You can try the latest version to see if it works.

**Comment by ctgraham** [comment]
Hi, @Caligula1022 .  Hope you are well.

The exposure of port 80 resolved the connection failures.  I also committed a change to broadly open CORS to the API in ccvg-integral:
https://github.com/ulsdevteam/ccvgd-integral/commit/8a4396ff86e01bbbe709d81ff6eb744b80c817af

This allows the Angular application to interact with the API, but I am still seeing 500 errors from the API in response to the `/advancedsearch` endpoint.

Are you still working on any of these?  If not, I can provide specific error messages.

**Comment by Caligula1022** [comment]
I don't seem to be experiencing this problem. Please send me the specific error messages.

From: Clinton Graham ***@***.***>
Date: Monday, February 27, 2023 at 11:54 AM
To: ulsdevteam/ccvgd-integral ***@***.***>
Cc: Yifei Tai ***@***.***>, Mention ***@***.***>
Subject: Re: [ulsdevteam/ccvgd-integral] Use WSGI server for API (Issue #8)

Hi, @Caligula1022<https://github.com/Caligula1022> . Hope you are well.

The exposure of port 80 resolved the connection failures. I also committed a change to broadly open CORS to the API in ccvg-integral:
8a4396f<https://github.com/ulsdevteam/ccvgd-integral/commit/8a4396ff86e01bbbe709d81ff6eb744b80c817af>

This allows the Angular application to interact with the API, but I am still seeing 500 errors from the API in response to the /advancedsearch endpoint.

Are you still working on any of these? If not, I can provide specific error messages.

**Comment by Caligula1022** [comment]
The problem seems to be with permissions. I increased the read/write permission of the file temp_write.csv, now I can use download normally in my test without the 500 error. You can try it now.

**Comment by ctgraham** [comment]
I pulled the latest code with the `chmod`, but I still get a 500 error:

From a fresh `docker compose up -d --build`, I select:
![image](https://user-images.githubusercontent.com/7001322/221660824-680468ab-b0ab-4522-9941-097d42285001.png)

Then I click search.

The Browser reports:
> 后端返回报错 !  
  error message: Http failure response for https://api.chinesevillagedata.library.pitt.edu/advancesearch: 500 Internal Server Error

The docker logs report:
```
172.20.0.5 - - [27/Feb/2023:19:10:31 +0000] "OPTIONS /advancesearch HTTP/1.1" 200 407 "https://x.chinesevillagedata.library.pitt.edu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"
[Mon Feb 27 19:10:31.180766 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664] mod_wsgi (pid=10): Exception occurred processing WSGI script '/var/www/apache-flask/apache-flask.wsgi'.
[Mon Feb 27 19:10:31.180971 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664] Traceback (most recent call last):
[Mon Feb 27 19:10:31.180996 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/var/www/apache-flask/app_func/advance_search.py", line 169, in advanceSearch
[Mon Feb 27 19:10:31.181003 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     f = open(os.path.join(path, "app_func", "multiple_csv", "{}_{}.csv".format(village_id_title, item)), 'w',
[Mon Feb 27 19:10:31.181022 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664] FileNotFoundError: [Errno 2] No such file or directory: '/var/www/apache-flask/app_func/multiple_csv/1_2_village.csv'
[Mon Feb 27 19:10:31.181034 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]
[Mon Feb 27 19:10:31.181039 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664] During handling of the above exception, another exception occurred:
[Mon Feb 27 19:10:31.181044 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]
[Mon Feb 27 19:10:31.181054 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664] Traceback (most recent call last):
[Mon Feb 27 19:10:31.181094 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
[Mon Feb 27 19:10:31.181099 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     return self.wsgi_app(environ, start_response)
[Mon Feb 27 19:10:31.181109 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
[Mon Feb 27 19:10:31.181114 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     response = self.handle_exception(e)
[Mon Feb 27 19:10:31.181123 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
[Mon Feb 27 19:10:31.181128 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     reraise(exc_type, exc_value, tb)
[Mon Feb 27 19:10:31.181137 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
[Mon Feb 27 19:10:31.181142 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     raise value
[Mon Feb 27 19:10:31.181152 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
[Mon Feb 27 19:10:31.181157 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     response = self.full_dispatch_request()
[Mon Feb 27 19:10:31.181167 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
[Mon Feb 27 19:10:31.181173 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     rv = self.handle_user_exception(e)
[Mon Feb 27 19:10:31.181183 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
[Mon Feb 27 19:10:31.181187 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     reraise(exc_type, exc_value, tb)
[Mon Feb 27 19:10:31.181196 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
[Mon Feb 27 19:10:31.181199 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     raise value
[Mon Feb 27 19:10:31.181207 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
[Mon Feb 27 19:10:31.181211 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     rv = self.dispatch_request()
[Mon Feb 27 19:10:31.181218 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
[Mon Feb 27 19:10:31.181221 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     return self.view_functions[rule.endpoint](**req.view_args)
[Mon Feb 27 19:10:31.181228 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]   File "/var/www/apache-flask/app_func/advance_search.py", line 172, in advanceSearch
[Mon Feb 27 19:10:31.181232 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664]     f = open(os.path.join(path, "app_func", "multiple_csv",
[Mon Feb 27 19:10:31.181243 2023] [wsgi:error] [pid 10:tid 140399294289664] [remote 172.20.0.5:42664] FileNotFoundError: [Errno 2] No such file or directory: '/var/www/apache-flask/app_func/multiple_csv/1_2_village.csv'
172.20.0.5 - - [27/Feb/2023:19:10:31 +0000] "POST /advancesearch HTTP/1.1" 500 828 "https://x.chinesevillagedata.library.pitt.edu/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/110.0"
```

**Comment by Caligula1022** [comment]
I don't why we have different default villages lists.
In my test after i run **docker compose up -d --build**. Wait for some time until the database is loaded. Then my select like this.
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/89871210/221663896-d8547eac-51c6-45a5-8a57-f20ec44d42df.png">
And the result is:
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/89871210/221664085-e154a0e9-5048-4ceb-bc7c-3fb622dfa36b.png">
No errors.

**Comment by ctgraham** [comment]
In branch `wsgi_test_backend`, there is currently no "app_func/multiple_csv" folder.  You probably have it as an untracked file from the `ccvgd-backend` branch.  This folder should probably be present, with a ".gitkeep" file.

**Comment by Caligula1022** [comment]
Oh, got it!
Submitted.

**Comment by ctgraham** [comment]
This resolved the HTTP/500 error for me.  I have another issue to report, but I will close this one.
